# Generated by Django 4.1.3 on 2022-12-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_smart_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smart',
            name='sale',
        ),
    ]
